name: Run meta pytest suite on repo

on:
  pull_request:
  push:

jobs:
  run-test:
    if: ${{ endsWith(github.repository, '-auto-template')  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install cookiecutter
        run: uv pip install --system -r requirements.dev.txt

      - name: run pytest
        run: uv run --with pytest pytest